const data ={
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            Category:'Shirts',
            image:'/images/p1.jpg',
            price:100,
            brand:'Nike',
            reting:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas fit Shirt',
            Category:'Shirts',
            image:'/images/p2.jpg',
            price:120,
            brand:'Adidas',
            reting:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste free Shirt',
            Category:'Shirts',
            image:'/images/p3.jpg',
            price:220,
            brand:'Lacoste',
            reting:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            Category:'Pants',
            image:'/images/p4.jpg',
            price:150,
            brand:'Nike',
            reting:4.5,
            numReviews:14,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Puma Slim Pants',
            Category:'Pants',
            image:'/images/p5.jpg',
            price:120,
            brand:'Puma',
            reting:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Adidas fit Pant',
            Category:'Pants',
            image:'/images/p6.jpg',
            price:139,
            brand:'Adidas',
            reting:4.5,
            numReviews:20,
            description:'high quality product',
        },
    ]
};
export default data;